### ISSUE TITLE
Use RFC3339 for timestamps

### ISSUE THREAD

**Issue by mdom** [buckket/twtxt#103]
Would it be possible to change the specification of a message to include a rfc3339 timestamp? ISO 8601 is a lot harder to parse and allows constructs like 2016-W15-03 that are not parsed correctly by the current parser. I checked 55 twtxt files and everybody is using rfc3339, so it would be easy to make the change now.

**Comment by kdave** [comment]
Such change would be better done sooner than later.

**Comment by DracoBlue** [comment]
:+1:

**Comment by quite** [comment]
I agree. RFC3339 is the way (which by the way requires a timezone (or Z), and timezone must have a colon)

**Comment by buckket** [comment]
Yes, this seems reasonable. The official twtxt client already complies to RFC3339, no further change needed there. We would only have to change the specification.
