### ISSUE TITLE
Hide posts from the future

### ISSUE THREAD

**Issue by DracoBlue** [buckket/twtxt#11]
At the moment I see this in my timeline:

``` 
➤ erlehmann (82 years from now):
I am also from the far future, but with another timestamp.

➤ erlehmann (82 years from now):
I am from the far future, bow before me!
```

since http://daten.dieweltistgarnichtso.net/tmp/docs/twtxt posted:

```
2099-01-01T00:00:00Z	I am from the far future, bow before me!
2099-01-01T00:00:01+00:00	I am also from the far future, but with another timestamp.
```

to be on top of every timeline ;).

Maybe an option to hide posts from the future would be useful?

**Comment by buckket** [comment]
Already fixed this here: https://github.com/buckket/twtxt/commit/523ab985f7cfb1c66be856ccc52859a48b6a8e5e, but I haven’t released a new version since.
