### ISSUE TITLE
Timeline sorting

### ISSUE THREAD

**Issue by timofurrer** [buckket/twtxt#16]
At the moment I'm not sure if I'm happy with the default sorting order (descending) of the tweets in the timeline...

If I don't use a pager I usually want the tweets in an ascending order - the newest tweets in the bottom because these are those I care most about and I do not want to scroll to the beginning. This is different if I use a pager because these start at the top ...

What are your thoughts? 
What do you think about changing the default sorting order dynamically depending on the given pager option?

**Comment by buckket** [comment]
Already implemented in the current dev version! Will ship with the next release. See #5

**Comment by timofurrer** [comment]
I agree with the *explicit better then implicit*.  And it doesn't seem to bad if the pager has the newest tweets in the bottom.

I'll close this one!

:cake:
