### ISSUE TITLE
Doesn’t work with Python 3.11

### ISSUE THREAD

**Issue by gergelypolonkai** [buckket/twtxt#168]
There are some quirks used throughout the repo that doesn’t work with newer Python versions, like `asyncio.coroutine`:

> Deprecated since version 3.8, will be removed in version 3.11: Use [async def](https://docs.python.org/3/reference/compound_stmts.html#async-def) instead.

– Python3’s [asyncio documentation](https://docs.python.org/3/library/asyncio-task.html#asyncio.coroutine)

`async def`, on the other hand, works fine since Python 3.5 (doesn’t work with the other Python version configured in `tox.ini`, 3.4, though). But since even 3.5 is EOL for about 2 years now, i think it would be safe to move to this method.

**Comment by buckket** [comment]
Code now works with Python 3.10 and should also be compatible with 3.11.
