### ISSUE TITLE
Tweet Spell check

### ISSUE THREAD

**Issue by Samathy** [buckket/twtxt#30]
I'm not particularly good at spelling, and rely heavily on spellcheck to get things right.
It should be quite simple to pipe a tweet into aspell before actually sending it, notifying the user if there are any words spelt incorrectly.

I should be able to do this myself, Just thought I'd post an issue to get suggestions before attempting it. (read - Give me a few days, I'd like to do it myself, don't do it for me!.)

**Comment by timofurrer** [comment]
hmm ... I don't like this. I want to use abbreviations, urls, foreign languages etc without a spell checking complaining about it.

Could you make something work with an alias? Or with piping instead?

```bash
echo "worng sepllt" | fancyspellchecker | twtxt tweet
```

However, this only makes sense if your spell checker fixes the mistakes - and wouldn't have control what would be tweeted in the end.

Maybe implement a generic pre-tweet hook option? In your case this would be a spell checker?

**Comment by Samathy** [comment]
Okay! I added a little snippet which asks the user if they just want to sent the tweet anyway without making any changes. Its almost like a "Check to make sure button"

(Requires GNU/aspell to be installed.)

**Comment by buckket** [comment]
See https://github.com/buckket/twtxt/pull/35#issuecomment-181333063. I’d rather see stuff like implemented using a plugin system / post_tweet_hook.

**Comment by Samathy** [comment]
That makes sense. I might maintain this patch until you have a plugin system working.

**Comment by buckket** [comment]
Closing this for now. Will come back to it later when we have a plugin system ready.
