### ISSUE TITLE
failing to write to the twtxt file doesn't abort execution

### ISSUE THREAD

**Issue by kitchen** [buckket/twtxt#33]
https://github.com/buckket/twtxt/blob/master/twtxt/cli.py#L72-L73

If that fails, a nice error message is reported and execution continues as usual, including executing the `post_tweet_hook`. I feel like this is incorrect behavior, and that it should abort immediately if writing the file fails.

**Comment by kitchen** [comment]
having a framework for surfacing runtime errors to the user in a Nice Way™ would also be useful in #32

**Comment by buckket** [comment]
Execution doesn't continue if `add_local_tweet()` returns False or raises an Exception.
