### ISSUE TITLE
Create a Formula for Homebrew

### ISSUE THREAD

**Issue by buckket** [buckket/twtxt#50]
Don’t own a Mac any more, so I can’t test or write it myself, but it would be nice to have.

**Comment by shakna-israel** [comment]
I could take a crack at this. I have an iMac with el Capitane, atm.

**Comment by buckket** [comment]
Useful resources:
- https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Homebrew-and-Python.md
- https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Python-for-Formula-Authors.md

Plus: there are some Python CLI tools in homebrew already:
https://github.com/Homebrew/homebrew/blob/7b3963ee1da7f0a4f97a28886efcff2cb88d821c/Library/Formula/httpie.rb

**Comment by shakna-israel** [comment]
Sorry about the time on this, just got waylaid by a couple things. 

There is a question however:

Most products distributed with Homebrew tend to be cutting edge, along the lines of Gentoo. 

But, I could use git tags(github releases) to do some version pinning. 

Basically depends on how sure we are that the master branch won't be incredibly buggy. 

Can we simply trust in the Unittests, or should we match the git tagged versions?

**Comment by timofurrer** [comment]
I'd highly recommend to use the official version tags.

**Comment by buckket** [comment]
Yeah, better use the the tagged releases. Using master only leads to confusion when half-implemented or undocumented features are beging shipped to the end user.

**Comment by shakna-israel** [comment]
Sure thing, I'll try to link to latest.

**Comment by shakna-israel** [comment]
Update:

There's an open pull request at [#49714](https://github.com/Homebrew/homebrew/pull/49714).

Unfortunately, Click is causing some issues with brew-test bot.

```
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Either run this under Python 2 or consult http://click.pocoo.org/python3/ for mitigation steps.
```

Just need to find a work around.

**Comment by buckket** [comment]
@shakna-israel Cool! Bet there is a way to circumvent this. But why have you listed `six` as a dependency for twtxt? That’s not needed! (Or has that something to do with how homebrew works?)

**Comment by shakna-israel** [comment]
Nope, just something that homebrew-poet picked up. I'll drop the dependency.

Just having issues with Travis only having en_US.UTF-8, but click wanting C.UTF-8... Hopefully some environment variable should be able to trick it.

**Comment by buckket** [comment]
You can try something like:
```
export LC_ALL=en_US.utf-8
export LANG=en_US.utf-8
```
before calling `twtxt` in the test section.

**Comment by buckket** [comment]
Also should the test command run something that doesn’t fail as well as do something meaningful. Thinking of writing a default config file and then call `twtxt -c config timeline`.

**Comment by buckket** [comment]
Something like: https://gist.github.com/buckket/f5a09fb41d8c1712f40e (regarding the test)

**Comment by buckket** [comment]
Ok, `six` is required by `python-dateutil`, missed that. So leave it there! :bow:

**Comment by shakna-israel** [comment]
Seems like the test builds pass now. See [Jenkins 43122](http://bot.brew.sh/job/Homebrew%20Pull%20Requests/43122/).

Needed to have a twtxt.txt file present, as well as the configuration.

**Comment by shakna-israel** [comment]
Merged in [homebrew](https://github.com/Homebrew/homebrew/commit/3a28bef14ce76cc614c46c238be370f1a2b420b0).

**Comment by buckket** [comment]
Thanks, @shakna-israel!
