### ISSUE TITLE
Add support for microformats and/or web mentions 

### ISSUE THREAD

**Issue by eli-oat** [buckket/twtxt#52]
I think twtxt would fit well into the [IndieWebCamp ecosystem](http://indiewebcamp.com/), particularly with support for [webmentions](http://indiewebcamp.com/webmention) and [microformats](http://microformats.org/wiki/microformats2)

**Comment by buckket** [comment]
Looks interesting. Thought about supporting webmentions, but the problem I see so far, is that we don’t really have a way to permalink a single twtxt tweet just yet (and I’m not even sure if this is something I would ever want to implement…)

I will keep this in my mind though, while figuring out the whole metadata situation!

**Comment by eli-oat** [comment]
Groovy! 

I haven't actually gotten twtxt up and running on anything by my local machine, yet, but I was thinking of writing a PHP thing to handle webmentions. I'll let you know if I do it! Just gotta find the time. :smile:
