### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by timofurrer** [buckket/twtxt#54]
I just submited a PR #53 to establish a sphinx documentation.
It would be nice to extend this documentation to cover the major features and implementation details of twtxt.

**Comment by buckket** [comment]
Thanks, this is very useful!

**Comment by buckket** [comment]
Seems to work: http://twtxt.readthedocs.org/en/latest/

**Comment by timofurrer** [comment]
Looks good! Thanks for uploading. :cake:

**Comment by buckket** [comment]
Still needs some work obviously. And I definitely like to expand the API section of our documentation, as twtxt can be used not only as a CLI-program, but also as a library for other tools.
