### ISSUE TITLE
Implement caching to avoid downloading whole files over and over again

### ISSUE THREAD

**Issue by buckket** [buckket/twtxt#7]
Idea from detaro on Hacker News:
> Make the ETAG the size, send a range request for only the bytes you haven't seen already?

Sounds cool, but If someone changes or deletes older status updates this might cause problems. 

Simpler: ``If-Modified-Since`` would help to avoid downloading the file if nothing changed, but then again if something changed we would have to grab the whole file.

**Comment by DracoBlue** [comment]
:+1: for "modified since" or normal "etag" behaviour (Status Code: 304 Not Modified) ;)

I think it's ok to redownload the entire file, IF something changed.

**Comment by timofurrer** [comment]
Like the idea! I agree with @DracoBlue .. probably not a big deal for now to download the whole file again ..

**Comment by buckket** [comment]
`If-Modified-Since` seems the way to go. Will implement soon.

**Comment by buckket** [comment]
Ok, my implementation seems to work, but now we have to decide on how we make use of caching transparently. 

Should we only consider using the cache when we get a 304 HTTP response or also request cached content when we have no connectivity at all or get a 4xx, 5xx response from the remote server?
