### ISSUE TITLE
How to pronounce 'twtxt'?

### ISSUE THREAD

**Issue by buckket** [buckket/twtxt#81]
Suggestions anyone? :grimacing:

**Comment by eli-oat** [comment]
"Twetext"

Like "wet" and "text" shoved together with a t at the start?

**Comment by kaikubasta** [comment]
twat xtreme

**Comment by tedder** [comment]
I think of it as "t w text".

**Comment by mkody** [comment]
Looks like "Twee text" for me.

**Comment by ruilorenzetti** [comment]
I think so that Kody is the better choice, because represents some form a
microblog

**Comment by Altoyyr** [comment]
I also vote for "TweeText" because It is not that far off and easy to pronounce.

**Comment by erlehmann** [comment]
two-text

**Comment by TeddyDesTodes** [comment]
I Vote for "Raider"

**Comment by buckket** [comment]
TweeText it is. ;3
