### ISSUE TITLE
Pre/post hooks should check return value

### ISSUE THREAD

**Issue by kdave** [buckket/twtxt#85]
post_tweet_hook = /bin/false followed by 'twxtxt tweet' succeeds, no messages. While the current semantics don't specify the behaviour, I'd expect that there should be some way how to get the feedback from the hooks.
Possible semantics:
* if post/pre _tweet_hook returns with nonzero code, print the stdout/stderr
* keep current as-is, add new hooks that will be strict about the hook result

**Comment by buckket** [comment]
For now this should do: https://github.com/buckket/twtxt/commit/59c7aec517e03c516e682d449b1ba04c85a0e689

**Comment by kdave** [comment]
Works for me, thanks.

**Comment by buckket** [comment]
> if post/pre _tweet_hook returns with nonzero code, print the stdout/stderr
Implemented.
