### ISSUE TITLE
twtxt has very low color contrast in terminal emulator

### ISSUE THREAD

**Issue by erlehmann** [buckket/twtxt#89]
See picture (using dev version with Atom/RSS support, following a podcast feed):
![twtxt-contrast-fail](https://cloud.githubusercontent.com/assets/60905/13090773/00345f1c-d4f8-11e5-9247-273779b68480.png)

Terminal emulator is ROXTerm. Any idea what could cause this?

**Comment by mkody** [comment]
It depends on your color scheme. Could be like this (lxterminal, default colors)
![hniynij](https://cloud.githubusercontent.com/assets/843787/13092379/e84229a4-d4ff-11e5-8441-03a9d393c594.png)

Or like this (iTerm, Solarized Dark)
![4ige0](https://cloud.githubusercontent.com/assets/843787/13092464/665e8cb0-d500-11e5-849c-d9e39d99b64f.png)

**Comment by erlehmann** [comment]
It seems that with the default color scheme twtxt is unreadable.

**Comment by timofurrer** [comment]
> It seems that with the default color scheme twtxt is unreadable.

The default depends on your terminal emulator ... I've got a good contrast.

**Comment by buckket** [comment]
Yes indeed, it’s up to you to configure your terminal emulator so that you can use it properly.
