### ISSUE TITLE
Display absolute time instead of relative time

### ISSUE THREAD

**Issue by erlehmann** [buckket/twtxt#90]
The relative time format displayed by twtxt (“2 hours ago”) makes it harder to comprehend the timeline.

First, it is relative not to the current time (when the user is reading the text), but to the time when the command was invoked. If one invokes the command and reads the output later, the information is no longer accurate. This also means one cannot use the twtxt client to generate a web page with a timeline unless it is regenerated very frequently.

Second, it has a very low resolution – I now have three entries in my timeline that have a time of “9 days ago”. I have no way to find out if that was 9 days ago in the morning or 9 days ago in the evening with the current display.

I therefore propose displaying the time always in an absolute form, taking the user's timezone into account. This could also eliminate the dependency on the “humanize“ library, which twtxt uses to turn the timestamps into the fuzzy human readable times shown right now.

**Comment by timofurrer** [comment]
:+1: I like that.
Maybe we can make it configurable if someone really want to use the relative times.

**Comment by erlehmann** [comment]
I think it should be removed in the interest of bloat reduction. It can be made an optional plugin later on! ☺
